### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by smaistre** [YunoHost-Apps/baikal_ynh#13]
I get an error after the installation.

```
Incomplete installation

Baïkal dependencies have not been installed. Please, execute "composer install" in the folder where you installed Baïkal.
```

**Comment by vmerlet** [comment]
Same problem here.

I tried removing and reinstalling baikal using yunohost api :
yunohost app remove baikal
yunohost app install baikal

Problem still present...

**Comment by julienmalik** [comment]
Can you paste the full installation log please, using :

```
$ yunohost app install baikal --debug
```

or grabbing them from the yunohost log files

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/513

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
