### ISSUE TITLE
Check if the caldav/cardav uri are available on the server before installing

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost-Apps/baikal_ynh#17]
Hello,

To works as expected, baikal needs to have control of both `/.well-known/carddav` and `/.well-known/caldav` as specified here https://github.com/YunoHost-Apps/baikal_ynh/blob/521dfc72dcaa9db6becf1eb96f5e1d2fe528294f/conf/nginx.conf#L1-L6

Those 2 paths are unique to a domain. This mean that if another app tries to handle those 2 paths, the nginx configuration will collide and nginx won't be able to reload (and won't start at the next reboot thus breaking all YunoHost).

This situation can happen (and has happen) if the user:

* install owncloud
* then install baikal

Owncloud app has a mecanism to prevent this conflit from happening as you can see here https://github.com/YunoHost-Apps/owncloud_ynh/blob/2b30543b5e53fe34e5380c3b3972d3dfc02489c7/scripts/install#L76 https://github.com/YunoHost-Apps/owncloud_ynh/blob/2b30543b5e53fe34e5380c3b3972d3dfc02489c7/scripts/_common.sh#L75-L82

But this mecanism only works if owncloud is installed after baikal.

I see to problems here:

* at least, baikal installation should have failed on a failed nginx reload
* baikal app should also check if this resource is available
* an understandable error message should be displayed

We can't expect our regular users to understand the reason behind all of this apart from "you can only have one app the handles caldav/carddav per domain" since the reason is very technical.

In a more global perspective, this mean that we should have mecanism if YunoHost to request "unique per domain resources" or more generally "unique resources" or something similar to avoid those conflicts. But this is a long term development that will need to be taken into account by apps.

Kind regards,

**Comment by Psycojoker** [comment]
I've created a ticket in the redmine for the biggest discussion https://dev.yunohost.org/issues/684

**Comment by alexAubin** [comment]
Bumpzor ... we regularly have people getting caught in this issue : https://forum.yunohost.org/t/the-operation-install-baikal-application-has-failed/5884
