### ISSUE TITLE
Base URI broken after upgrade

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/baikal_ynh#33]
Hi,

since the last upgrade (https://github.com/YunoHost-Apps/baikal_ynh/commit/e5bc9f8abc6660bd93be12551fd765f47049904d) my install was broken. All the base URIs became:

```php
# Should begin and end with a "/"
define("BAIKAL_CARD_BASEURI", "//card.php/");

# Should begin and end with a "/"
define("BAIKAL_CAL_BASEURI", "//cal.php/");

# Should begin and end with a "/"
define("BAIKAL_DAV_BASEURI", "//dav.php/");
```

whereas the previous and correct values are:

```php
# Should begin and end with a "/"
define("BAIKAL_CARD_BASEURI", "/card.php/");

# Should begin and end with a "/"
define("BAIKAL_CAL_BASEURI", "/cal.php/");

# Should begin and end with a "/"
define("BAIKAL_DAV_BASEURI", "/dav.php/");
```

i guess the `__PATH__` is equal to `/` here: https://github.com/YunoHost-Apps/baikal_ynh/blob/master/conf/config.system.php#L42-L48.

I am using the app on its own subdomain, ie. `baikal.mydomain.tld`, not on a subpath.

**Comment by nicofrand** [comment]
Many thanks for the app BTW!

**Comment by Gofannon** [comment]
On my server, Baikal is installed on a subdomain and runs

**domain:** https://example.org/baikal/

**config screenshot**
![image](https://user-images.githubusercontent.com/17145502/56301409-0c10c800-6138-11e9-95ac-6951acd4949c.png)

**Comment by nicofrand** [comment]
@Gofannon This is not a subdomain then? This is a subdirectory?

**Comment by Gofannon** [comment]
> 
> 
> @Gofannon This is not a subdomain then? This is a subdirectory?

Yes indeed !

**Comment by nwallace** [comment]
This issue affected me on a new installation as well. By default, the base URIs were set as pictured below (with two leading slashes):
![image](https://user-images.githubusercontent.com/1614172/59559296-72478900-8fc9-11e9-9a28-6fa7a26569c6.png)

I was getting a 500 error when I tried to connect either a calendar or address book:
> Requested uri (/card.php/addressbooks/me/default) is out of base uri (//card.php/)

I took an educated guess and removed one of the leading slashes, and then I could add my contacts and calendars and that fixed the problem:
![image](https://user-images.githubusercontent.com/1614172/59559328-13ceda80-8fca-11e9-998f-c3a50c979dc7.png)

**Comment by nwallace** [comment]
Just upgraded to 0.5.3 from 0.4.something and this problem was re-introduced, despite my previous manual fix

**Comment by AkselRocks** [comment]
After upgrading today I get an 500 error in Davx5 app and error in thunderbird on all calendars.

log: https://paste.yunohost.org/raw/izexebuwid

**Comment by nicofrand** [comment]
@AkselRocks Edit your config file like suggested above?

**Comment by AkselRocks** [comment]
@nicofrand yes!
1) The suggestion/thread is one year old. I believed this bug has been solved already and it is a new one.
2) I thought I had deleted my comment ...
