### ISSUE TITLE
php-xml, php-mbstring dependencies missing

### ISSUE THREAD

**Issue by m4de** [YunoHost-Apps/baikal_ynh#40]
After a fresh Yunohost + Baikal installation, I could not open e.g. Baikal/dav.php because of a DOMDocument error. After installing php-xml and php-mbstring by hand the pages started to work.

**Comment by kay0u** [comment]
Hi,

Thank you for your report, I just opened a PR to fix that:

https://github.com/YunoHost-Apps/baikal_ynh/pull/41

**Comment by kay0u** [comment]
Fixed by #37
