### ISSUE TITLE
Maintainer ?

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/baikal_ynh#47]
I've read on the forum (https://forum.yunohost.org/t/about-the-end-of-official-apps-in-yunohost/10530/8) that this app is looking for a maintainer. 
@kay0u are you already maintaining this app, do you need help ?

**Comment by kay0u** [comment]
I don't have so much time to spend on this app, but we could maintaining this app together if you want.

**Comment by Salamandar** [comment]
OK, why not :) I'll familiarize myself with the project and will push merge requests i guess.
