### ISSUE TITLE
Restore Baikal settings after upgrade

### ISSUE THREAD

**Issue by Dazeilad** [YunoHost-Apps/baikal_ynh#51]
Hi,

I just spent the afternoon trying to understand why I lost access to my calendar and address books right after the upgrade...
Now that I found out why, I wish to share the solution, and I hope you can modify the upgrade script to implement it (sorry I don't see how to code that).

1. First problem was the same as [here](https://github.com/YunoHost-Apps/baikal_ynh/pull/50), and seems to be solved, just waiting a merge.
2. Second problem is that the following settings of Baikal changed : Server Time Zone (does not concern my issue, but I still had to correct it) and the **WebDAV authentication type** (it used to work with "Digest" for me, but was set to LDAP-User-Bind after the upgrade).

![image](https://user-images.githubusercontent.com/64801705/80996487-2b13f200-8e40-11ea-93fe-461aa60d4abe.png)

So I suggest to add some functions in the upgrade script to keep the previous settings during the upgrade.

Thanks for maintaining this very convenient app by the way :+1:  :smile_cat:

**Comment by tompatulpan** [comment]
Thanks, this has bugged me for a long time and now I understand the problem!
updated to 0.7.1 and have had two problems
1. lost my admin password and had to reset with https://so.nohost.me/yunohost/admin/#/apps/baikal/actions
2. authentication type changed.

**Comment by Dazeilad** [comment]
Hi, the last update (0.9.3) has again this problem... I had to correct the same parameters after the upgrade.

**Comment by tompatulpan** [comment]
Me too

**Comment by ericgaspar** [comment]
should be fixed on testing

**Comment by Dazeilad** [comment]
Issue still live... After upgrading to 0.9.4.
