### ISSUE TITLE
An another FPM instance seems to already listen on php7.0-fpm-baikal.sock

### ISSUE THREAD

**Issue by 6-ril** [YunoHost-Apps/baikal_ynh#54]
Hello !

Following an update (maybe Baikal, but I'm not sure ... yes, I should have checked that my system works well after each update ...) the php7.0-fpm service doesn't start. I have 502 Bad Gateway errors on some applications ...

In the log I have this:

ERROR: An another FPM instance seems to already listen on /var/run/php/php7.0-fpm-baikal.sock

I assumed that baikal now uses another version of php, but when configuring php7.0, there is always a link ...

In the /etc/php/7.0/fpm/pool.d/ folder, I still have a baikal.conf file
So I created a sub-folder in case :

sudo mkdir /etc/php/7.0/fpm/pool.d/old

and I moved the file :

sudo mv /etc/php/7.0/fpm/pool.d/baikal.conf /etc/php/7.0/fpm/pool.d/old/baikal.conf

I was able to restart the service and all the applications seem to be working.

This post referred me to: https://stackoverflow.com/questions/23423425/errors-with-php-fpm-sock

Is it possible that when updating, Baikal leaves some configuration file in previous PHP version ?

Cyril

**Comment by madtibo** [comment]
Hello,

Same issue for me.

files /etc/php/7.0/fpm/pool.d/baikal.conf /etc/php/7.3/fpm/pool.d/baikal.conf are the same.  
So I removed the one in the 7.0 folder.

I can now restart the services without problems.

Cordialement,
Thibaut

**Comment by madmaxlamenace** [comment]
Same issue 
find /etc/php/ -name "baikal*"
/etc/php/7.0/fpm/pool.d/baikal.conf
/etc/php/7.3/fpm/pool.d/baikal.conf
i just renamed the baikal.conf file in 7.0 to baikal.conf.migrated.to.7.3
cd /etc/php/7.0/fpm/pool.d/
mv baikal.conf baikal.conf.migrated.to.7.3
service php7.0 restart
And it worked
