### ISSUE TITLE
failed to upgrade from 0.6.1~ynh1 to 0.7.1~ynh1

### ISSUE THREAD

**Issue by tompatulpan** [YunoHost-Apps/baikal_ynh#56]
Hi,
failed to upgrade from 0.6.1\~ynh1 to 0.7.1\~ynh1

log - https://paste.yunohost.org/raw/iyutitahem
Local server is behind reverse proxy.

Any help much appreciated!
/T

**Comment by kay0u** [comment]
The technical problem seems to become from [here](https://github.com/YunoHost/yunohost/blob/1279755463100e6c4a0ba7d4b50f8f39658c8eac/data/helpers.d/apt#L261)

Can I have the result of this command please:
```
dpkg --list | grep "php7.0"
```

**Comment by tompatulpan** [comment]
Hi, 
this is the output;
`$ dpkg --list | grep "php7.0"
ii  php7.0-cli                            7.0.33-0+deb9u10                   amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                         7.0.33-0+deb9u10                   amd64        documentation, examples and common module for PHP
ii  php7.0-curl                           7.0.33-0+deb9u10                   amd64        CURL module for PHP
ii  php7.0-fpm                            7.0.33-0+deb9u10                   amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-gd                             7.0.33-0+deb9u10                   amd64        GD module for PHP
ii  php7.0-intl                           7.0.33-0+deb9u10                   amd64        Internationalisation module for PHP
ii  php7.0-json                           7.0.33-0+deb9u10                   amd64        JSON module for PHP
ii  php7.0-ldap                           7.0.33-0+deb9u10                   amd64        LDAP module for PHP
ii  php7.0-mbstring                       7.0.33-0+deb9u10                   amd64        MBSTRING module for PHP
ii  php7.0-mcrypt                         7.0.33-0+deb9u10                   amd64        libmcrypt module for PHP
ii  php7.0-mysql                          7.0.33-0+deb9u10                   amd64        MySQL module for PHP
ii  php7.0-opcache                        7.0.33-0+deb9u10                   amd64        Zend OpCache module for PHP
ii  php7.0-readline                       7.0.33-0+deb9u10                   amd64        readline module for PHP
ii  php7.0-xml                            7.0.33-0+deb9u10                   amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
`

**Comment by tompatulpan** [comment]
The update is working Ok after updating to Yunohost 4.08.

I think we can close this.
