### ISSUE TITLE
Cant reset admin password

### ISSUE THREAD

**Issue by JimFrostig** [YunoHost-Apps/baikal_ynh#65]
Hi!

After upgrading to the latest version (0.7.1~ynh2) I can no longer log in as admin with my password. I tried the actions described in the readme, but I get an error. Is there any other way to reset the password?

<img width="1151" alt="Bildschirmfoto 2022-04-06 um 08 58 51" src="https://user-images.githubusercontent.com/6785519/161914521-d00d6d20-bbb5-4f64-af08-2780e1a05aa8.png">
 
Greetings!

**Comment by ericgaspar** [comment]
actions are not suppoted (yet) in YunoHost. (this will be removed in the next version of the script). You can change the admin password in Baïkal admin interface.
