### ISSUE TITLE
Cannot authenticate after 0.9.3~ynh1 -> 0.9.3~ynh3 upgrade

### ISSUE THREAD

**Issue by baptabl** [YunoHost-Apps/baikal_ynh#82]
Hello! 🙂 

### Describe the bug

Cannot authenticate after 0.9.3~ynh3 upgrade.
Neither from Caldav clients (Thunderbird, iOS calendar app) nor the web interface as regular user on https://cal.XXXX.fr/cal.php.

It may be linked to https://github.com/YunoHost-Apps/baikal_ynh/issues/76.

@ericgaspar I saw that you recently worked on this app, did you change anything around login/LDAP parts of the code?

### Context

- Hardware: Raspberry Pi 4 8Go at home
- YunoHost version: 11.2.3
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: baikal 0.9.3~ynh3

### Steps to reproduce
Try to login to the web UI https://cal.XXXX.fr/cal.php, a clear XML response:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.3.1</s:sabredav-version>
  <s:exception>Error</s:exception>
  <s:message>Call to undefined function Baikal\Core\ldap_connect()</s:message>
</d:error>
```

The web admin UI with admin user works well.

### Expected behavior
Successful login.

### Logs

/var/log/nginx/cal.XXX.fr-error.log:
```
2023/08/31 14:04:54 [error] 1183#1183: *217 FastCGI sent in stderr: "PHP message: Error: Call to undefined function Baikal\Core\ldap_connect() in /var/www/baikal/Core/Frameworks/Baikal/Core/LDAPUserBindAuth.php:32
Stack trace:
#0 /var/www/baikal/Core/Frameworks/Baikal/Core/AbstractExternalAuth.php(64): Baikal\Core\LDAPUserBindAuth->validateUserPassExternal()
#1 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php(103): Baikal\Core\AbstractExternalAuth->validateUserPass()
#2 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(180): Sabre\DAV\Auth\Backend\AbstractBasic->check()
#3 /var/www/baikal/vendor/sabre/dav/lib/DAV/Auth/Plugin.php(135): Sabre\DAV\Auth\Plugin->check()
#4 /var/www/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\Auth\Plugin->beforeMethod()
#5 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit()
#6 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#7 /var/www/baikal/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()" while reading response header from upstream, client: 77.204.X.X, server: cal.XXX.fr, request: "GET /dav.php/calendars/bat/default/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm-baikal.sock:", host: "cal.XXX.fr"
```

**Comment by zcatav** [comment]
After the upgrade, have you tried logging into the baikal administrator account and re-activating it?

**Comment by baptabl** [comment]
> After the upgrade, have you tried logging into the baikal administrator account and re-activating it?

Hi @zcatav, thanks for your reply.

I just tried to upgrade once again from `0.9.3~ynh1` to `0.9.3~ynh3` (I had previously rollbacked, because no time to investigate this week) and everythinks works fine now... that's really strange.
