### ISSUE TITLE
Baikal admin interface does not list Yunohost users

### ISSUE THREAD

**Issue by bmp** [YunoHost-Apps/baikal_ynh#93]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

Baikal does not list the yunohost users in the admin interface. 

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 11.2.9.1 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain:
- Using, or trying to install package version/branch: Used the instructions at https://forum.yunohost.org/t/baikal-cal-and-carddav-server/3969/25 to move to the testing branch
- If upgrading, current package version: 0.9.4~ynh1

### Steps to reproduce

   1. *Go to https://domain/baikal/admin/*
   2. *Type in password and click on 'Authenticate'*
   3. *Check number of users under statistics'*
   4. *No users are shown, i.e zero users*

### Expected behavior

*List all the users in yunohost (currently 2 on my server)*

### Logs

*If applicable and useful, add screenshots to help explain your problem.*

1. Yunohost-Baikal: 
![Screenshot 2024-01-09 at 14-43-16 Baïkal 0 9 4 Web Admin](https://github.com/YunoHost-Apps/baikal_ynh/assets/1095177/8bd6c604-8e15-49ff-a28c-3e596ea47af8)

2. Yunohsot-admin: 
![Screenshot 2024-01-09 at 14-45-08 Users YunoHost Admin](https://github.com/YunoHost-Apps/baikal_ynh/assets/1095177/84ca9d76-5005-44e6-950f-13c9104de541)

**Comment by Toromtomtom** [comment]
Hi, the users in Baikal [are not created automatically, but when they log in to Baikal](https://yunohost.org/de/app_baikal). Can you try to log in to Baikal as one of the YNH users and then check the Admin dashboard again?

**Comment by bmp** [comment]
@Toromtomtom Thank you! I did that and the user is now listed. But now when I try to login through an application like DAVx5, I get the message that `Couldn't find CalDAV or CardDAV service.`

 Is there something wrong I am doing? I am using the `https://domain/baikal/dav.php` with the username and password from Yunohost.

**Comment by Toromtomtom** [comment]
One possible reason for this problem could be that `https://domain/baikal/dav.php` is protected by YNH's SSO. Did you make Baikal accessible for visitors or for YNH users only?

There is also an [ongoing discussion on the YNH forum](https://forum.yunohost.org/t/baikal-improvements/28015/4) about this.

**Comment by bmp** [comment]
@Toromtomtom Thank you! That solved the problem!
